version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fitlifeweb-backend
    ports:
      - "8080:8080"
    environment:
      # Configuracion de Supabase (Sera leida por application.properties si usamos ${DB_URL} etc.)
      - SPRING_PROFILES_ACTIVE=prod
      # - DB_URL=jdbc:postgresql://<SUPABASE_HOST>:5432/postgres
      # - DB_USERNAME=postgres
      # - DB_PASSWORD=<TU_PASSWORD>
    networks:
      - fitlife-net
    restart: unless-stopped

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: fitlifeweb-frontend
    ports:
      - "80:80" # Mapeamos el puerto 80 del host al 80 del contenedor Nginx
      - "5173:80" # Tambien mapeamos el puerto 5173 temporalmente para no romper los habitos locales
    depends_on:
      - backend
    networks:
      - fitlife-net
    restart: unless-stopped

networks:
  fitlife-net:
    driver: bridge
